name: Replace Moment 1.0.0

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  archived:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Moment 1.0.0 replacement completed from source 312b6fcbd7e4f83f04eb1c4cb680152504433256.'
